### ISSUE TITLE
[vim] plugin for jekyll syntax

### ISSUE THREAD

**Issue by fefas** [joedicastro/dotfiles#18]
Hello Joe,

I use you vimrc file and I find it great... thank you :)

The problem is: I am writing code that uses [Jekyll](http://jekyllrb.com/) and syntax error are showed. Check this example (I called it `index.html`):

```html
---
layout: default
title: Page Title
---

html text <!-- warning: plain text isn't allowed in <head> elements -->
```

I would try to add a new plugin, but I'm not sure, for example, how to skip normal `html` file and this type of `html` files. Could you please help me with this issue?

Thank you very much

**Comment by joedicastro** [comment]
Well, one solution that I can think is to change the filetype for those files, e.g. `tt2html` or `htmldjango` works well for those files. You can do it like this:

```vim
:set ft=htmldjango
```

or via the Unite menu, `[space] v`, choose `choose filetype` and then choose the right one.

Another way is to disable the Syntastic plugin when editing those files, with 

```vim
:SyntasticToggleMode` 
```

or via the Unite menu.

**Comment by fefas** [comment]
that was easy.. thanks :)

**Comment by joedicastro** [comment]
You're welcome! :)
